package com.ilygames.quizapp.data.model

/**
 * Represents a question fetched from Open Trivia DB or generated by Gemini AI.
 * Different from [Question] which uses optionA/B/C/D format.
 */
data class TriviaQuestion(
    val _id: String = "",
    val question: String,
    val options: List<String>,   // 4 shuffled options
    val answer: String,          // exact string matching one of options
    val explanation: String = "",
    val difficulty: String = "medium",
    val category: String = ""
)
